/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "Pin_3.h"
#include "Pin_3_aliases.h"
#include "Pin_4.h"
#include "Pin_4_aliases.h"
#include "Pin_5.h"
#include "Pin_5_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "cy_em_eeprom.h"
#include "CyLFClk.h"

/*[]*/

